package desu.inugram.core.plugins

// GENERATED by `pnpm run generate-grants` from sdk/types/grants.json.
// do not edit by hand - `pnpm run setup` regenerates it.

/** what a grant's scopes are drawn from, and so what validates one */
enum class ScopeKind {
    NONE,
    LIST,
    DOMAIN,
    FS_SIZE,
    RPC_METHOD,
    UPDATE_TYPE,
}

/** ordered by severity: a permission list takes the max */
enum class GrantTier {
    NEUTRAL,
    CAUTION,
    DANGEROUS,
}

/**
 * Every grant a manifest may ask for, and what it accepts. The catalogue is published to plugin
 * authors as `@inugram/plugin-types/grants.json`, so `inu check` refuses what the app refuses.
 *
 * What is deliberately *not* here: the android resources naming each grant in the permission
 * sheet. Those are compile-time ints, so `PluginInfoActivity` keeps its own table, pinned against
 * this one by `GrantCatalogTest`.
 */
object GrantCatalog {
    /** the `@plugin-api` level this app implements */
    const val PLUGIN_API = 1

    class Entry(
        val name: String,
        val scopes: ScopeKind,
        /** the closed vocabulary of a [ScopeKind.LIST] grant, empty for every other kind */
        val values: Set<String>,
        /** scope names accepted on top of the TL vocabulary the grant draws from */
        val extraValues: Set<String>,
        /** a takeover method is refused as a scope of this grant */
        val refusesTakeover: Boolean,
        val tier: GrantTier,
        /** how the grant reads when it names no scope at all, when that is worse than [tier] */
        val tierWhenUnscoped: GrantTier?,
    )

    private val ENTRIES: List<Entry> = listOf(
        Entry(
            name = "kv",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "fs",
            scopes = ScopeKind.FS_SIZE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "clipboard.write",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "clipboard.read",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.CAUTION,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "openUrl",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "onAppVisibilityChange",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "notifications.suppress",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "fetch",
            scopes = ScopeKind.DOMAIN,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = GrantTier.CAUTION,
        ),
        Entry(
            name = "account.read",
            scopes = ScopeKind.LIST,
            values = setOf("self", "peers", "messages", "dialogs", "history", "draft"),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = GrantTier.CAUTION,
        ),
        Entry(
            name = "account.write",
            scopes = ScopeKind.LIST,
            values = setOf("send", "edit", "delete", "forward", "react", "read", "typing", "draft"),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.CAUTION,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "onUpdate",
            scopes = ScopeKind.UPDATE_TYPE,
            values = emptySet(),
            extraValues = setOf("new_message", "edit_message", "delete_message"),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = GrantTier.CAUTION,
        ),
        Entry(
            name = "interceptUpdate",
            scopes = ScopeKind.UPDATE_TYPE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = GrantTier.CAUTION,
        ),
        Entry(
            name = "interceptSendMessage",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.CAUTION,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "invokeRpc",
            scopes = ScopeKind.RPC_METHOD,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = true,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = GrantTier.CAUTION,
        ),
        Entry(
            name = "interceptRpc",
            scopes = ScopeKind.RPC_METHOD,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = true,
            tier = GrantTier.NEUTRAL,
            tierWhenUnscoped = GrantTier.CAUTION,
        ),
        Entry(
            name = "takeout",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.CAUTION,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "unsafe.fs",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.DANGEROUS,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "unsafe.invokeRaw",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.DANGEROUS,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "unsafe.jvm",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.DANGEROUS,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "unsafe.xposed",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.DANGEROUS,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "unsafe.notificationCenter",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.DANGEROUS,
            tierWhenUnscoped = null,
        ),
        Entry(
            name = "unsafe.disableApiFiltering",
            scopes = ScopeKind.NONE,
            values = emptySet(),
            extraValues = emptySet(),
            refusesTakeover = false,
            tier = GrantTier.DANGEROUS,
            tierWhenUnscoped = null,
        ),
    )

    private val BY_NAME: Map<String, Entry> = ENTRIES.associateBy { it.name }

    private val DOMAIN = Regex("[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?)*")
    private val FS_SIZE = Regex("(\\d+)(kb|mb|gb)", RegexOption.IGNORE_CASE)

    private val TAKEOVER_METHODS: Set<String> = setOf(
        "account.getPasskeys",
        "account.deletePasskey",
        "account.registerPasskey",
        "account.initPasskeyRegistration",
        "account.registerDevice",
        "account.unregisterDevice",
        "account.deleteAccount",
        "account.changePhone",
        "account.getAuthorizations",
        "account.resetAuthorization",
        "account.acceptAuthorization",
        "account.verifyPhone",
        "account.verifyEmail",
        "account.resetPassword",
    )

    /** never delivered without `unsafe.disableApiFiltering`, so a grant naming one narrows to nothing */
    val UNDELIVERABLE_UPDATES: Set<String> = setOf("updateServiceNotification")

    val names: Set<String> get() = BY_NAME.keys

    fun entryOf(name: String): Entry? = BY_NAME[name]

    fun isDomain(scope: String): Boolean = DOMAIN.matches(scope)

    fun fsSizeMatch(scope: String): MatchResult? = FS_SIZE.matchEntire(scope.trim())

    /**
     * refused in `invokeRpc`/`interceptRpc` under every grant but `unsafe.disableApiFiltering`,
     * because holding one is a complete account takeover
     */
    fun isTakeoverMethod(name: String): Boolean =
        name.startsWith("auth.") || name in TAKEOVER_METHODS

    fun tierOf(name: String, scopes: List<String>?): GrantTier {
        val entry = BY_NAME[name] ?: return GrantTier.NEUTRAL
        val unscoped = entry.tierWhenUnscoped
        if (scopes == null && unscoped != null && unscoped > entry.tier) return unscoped
        return entry.tier
    }
}
