package desu.inugram.core.plugins

/** Generated by `pnpm run generate-tl-typings`. */
object TlCtorIds {
    private const val RESOURCE = "/tl_ctor_ids.txt"

    private class Table(
        val ids: Map<String, Set<Int>>,
        val methodNames: Set<String>,
        val updateNames: Set<String>,
    ) {
        /**
         * every id back to every name that claims it. A legacy variant shares its id with the live
         * constructor it replaced, and which of the two a caller would have seen first is hash
         * order, so the answer is the whole set: a question asked of one name must be asked of all.
         */
        val namesById: Map<Int, Set<String>> by lazy {
            val out = HashMap<Int, MutableSet<String>>(ids.size * 2)
            for ((name, set) in ids) for (id in set) out.getOrPut(id) { LinkedHashSet() }.add(name)
            out
        }
    }

    private val table: Table by lazy { parse() }

    private fun parse(): Table {
        val text = TlCtorIds::class.java.getResourceAsStream(RESOURCE)?.use { it.readBytes().toString(Charsets.UTF_8) }
            ?: throw IllegalStateException("$RESOURCE is missing from the classpath; run `pnpm run generate-tl-typings`")

        val ids = HashMap<String, Set<Int>>()
        val methodNames = HashSet<String>()
        val updateNames = HashSet<String>()
        for (line in text.lineSequence()) {
            if (line.isEmpty() || line.startsWith('#')) continue
            val parts = line.split(' ')
            val kind = parts[0]
            val name = parts[1]
            val hexIds = parts.subList(2, parts.size).mapTo(HashSet()) { it.toLong(16).toInt() }
            ids[name] = hexIds
            when (kind) {
                "m" -> methodNames.add(name)
                "u" -> updateNames.add(name)
            }
        }
        return Table(ids, methodNames, updateNames)
    }

    fun idsOf(name: String): Set<Int>? = table.ids[name]

    /** every name a constructor id is declared under, empty when no layer this build knows declares it */
    fun namesOf(id: Int): Set<String> = table.namesById[id].orEmpty()

    val methodNames: Set<String> get() = table.methodNames
    val updateNames: Set<String> get() = table.updateNames
    val allNames: Set<String> get() = table.ids.keys
}
