package desu.inugram.core.plugins

/** `tl_tables.txt` is gitignored, generated by `pnpm run generate-tl` and `pnpm run setup` */
object TlTables {
    private const val RESOURCE = "/tl_tables.txt"

    data class Gate(val word: Int, val bit: Int)

    class Table(
        val flagWords: List<String>,
        val namespaces: Set<String>,
        val nameOverrides: Map<String, String>,
        val idsByName: Map<String, Set<Int>>,
        /** legacy and current constructors can share an id, so checks must consider every name */
        val namesById: Map<Int, Set<String>>,
        val methodNames: Set<String>,
        val updateNames: Set<String>,
        val gatesById: Map<Int, Map<String, Gate>>,
        val int53ById: Map<Int, Set<String>>,
    )

    val table: Table by lazy { parse() }

    fun prewarm() {
        table
    }

    fun getConstructorIds(name: String): Set<Int>? = table.idsByName[name]

    /** empty when no known layer declares it */
    fun getConstructorNames(id: Int): Set<String> = table.namesById[id].orEmpty()

    val methodNames: Set<String> get() = table.methodNames
    val updateNames: Set<String> get() = table.updateNames
    val allNames: Set<String> get() = table.idsByName.keys

    /** stock declares hundreds of TL classes without the `TL_` prefix */
    fun readConstructorId(cls: Class<*>): Int? = try {
        val field = cls.getDeclaredField("constructor")
        if (java.lang.reflect.Modifier.isStatic(field.modifiers) && field.type == Integer.TYPE) {
            field.isAccessible = true
            field.getInt(null)
        } else {
            null
        }
    } catch (e: NoSuchFieldException) {
        null
    }

    private fun parse(): Table {
        val text = TlTables::class.java.getResourceAsStream(RESOURCE)?.use { it.readBytes().toString(Charsets.UTF_8) }
            ?: throw IllegalStateException("$RESOURCE is missing from the classpath; run `pnpm run generate-tl`")

        var flagWords = emptyList<String>()
        var namespaces = emptySet<String>()
        val nameOverrides = HashMap<String, String>()
        val idsByName = HashMap<String, MutableSet<Int>>()
        val namesById = HashMap<Int, Set<String>>()
        val methodNames = HashSet<String>()
        val updateNames = HashSet<String>()
        val gatesById = HashMap<Int, Map<String, Gate>>()
        val int53ById = HashMap<Int, Set<String>>()
        for (line in text.lineSequence()) {
            if (line.isEmpty() || line.startsWith('#')) continue
            val parts = line.split(' ')
            when (parts[0]) {
                "words" -> flagWords = parts.drop(1)
                "ns" -> namespaces = parts.drop(1).toHashSet()
                "name" -> nameOverrides[parts[1]] = parts[2]
                else -> {
                    val id = parts[0].toLong(16).toInt()
                    val names = LinkedHashSet<String>()
                    val gates = HashMap<String, Gate>()
                    val int53 = HashSet<String>()
                    for (i in 1 until parts.size) {
                        val token = parts[i]
                        val value = token.substring(2)
                        when (token[0]) {
                            'c', 'm', 'u' -> {
                                names.add(value)
                                idsByName.getOrPut(value) { HashSet() }.add(id)
                                if (token[0] == 'm') methodNames.add(value)
                                if (token[0] == 'u') updateNames.add(value)
                            }
                            'f' -> {
                                val eq = value.indexOf('=')
                                val bit = value.substring(eq + 1)
                                val second = bit.startsWith('+')
                                gates[value.substring(0, eq)] =
                                    Gate(if (second) 1 else 0, (if (second) bit.substring(1) else bit).toInt())
                            }
                            'i' -> int53.add(value)
                            else -> throw IllegalStateException("$RESOURCE: unknown token '$token' on constructor ${parts[0]}")
                        }
                    }
                    if (names.isNotEmpty()) namesById[id] = names
                    if (gates.isNotEmpty()) gatesById[id] = gates
                    if (int53.isNotEmpty()) int53ById[id] = int53
                }
            }
        }
        return Table(flagWords, namespaces, nameOverrides, idsByName, namesById, methodNames, updateNames, gatesById, int53ById)
    }
}
