package desu.inugram.ui.settings

// GENERATED by `pnpm run generate-grants` from sdk/types/grants.json.

import org.telegram.messenger.R

internal class GrantPresentation(val titleRes: Int, val iconRes: Int)

internal val KNOWN_GRANTS: Map<String, GrantPresentation> = mapOf(
    "fs" to GrantPresentation(R.string.InuPluginGrantFs, R.drawable.files_storage),
    "clipboard.write" to GrantPresentation(R.string.InuPluginGrantClipboardWrite, R.drawable.msg_copy),
    "clipboard.read" to GrantPresentation(R.string.InuPluginGrantClipboardRead, R.drawable.msg_copy),
    "openUrl" to GrantPresentation(R.string.InuPluginGrantOpenUrl, R.drawable.msg_link),
    "onAppVisibilityChange" to GrantPresentation(R.string.InuPluginGrantAppVisibility, R.drawable.menu_hide_gift),
    "notifications.suppress" to GrantPresentation(R.string.InuPluginGrantNotificationsSuppress, R.drawable.msg_mute),
    "fetch" to GrantPresentation(R.string.InuPluginGrantFetch, R.drawable.msg_language),
    "account.read" to GrantPresentation(R.string.InuPluginGrantAccountRead, R.drawable.msg_contacts),
    "account.write" to GrantPresentation(R.string.InuPluginGrantAccountWrite, R.drawable.msg_send),
    "onUpdate" to GrantPresentation(R.string.InuPluginGrantOnUpdate, R.drawable.msg_message),
    "interceptUpdate" to GrantPresentation(R.string.InuPluginGrantInterceptUpdate, R.drawable.msg_download),
    "interceptSendMessage" to GrantPresentation(R.string.InuPluginGrantInterceptSend, R.drawable.msg_edit),
    "invokeRpc" to GrantPresentation(R.string.InuPluginGrantInvokeRpc, R.drawable.msg_bot),
    "interceptRpc" to GrantPresentation(R.string.InuPluginGrantInterceptRpc, R.drawable.msg_log),
    "takeout" to GrantPresentation(R.string.InuPluginGrantTakeout, R.drawable.msg_download),
    "unsafe.fs" to GrantPresentation(R.string.InuPluginGrantUnsafeFs, R.drawable.files_storage),
    "unsafe.invokeRaw" to GrantPresentation(R.string.InuPluginGrantUnsafeInvokeRaw, R.drawable.msg_bot),
    "unsafe.jvm" to GrantPresentation(R.string.InuPluginGrantUnsafeJvm, R.drawable.inu_tabler_code),
    "unsafe.xposed" to GrantPresentation(R.string.InuPluginGrantUnsafeXposed, R.drawable.msg_replace),
    "unsafe.notificationCenter" to GrantPresentation(R.string.InuPluginGrantUnsafeNotificationCenter, R.drawable.msg_notifications),
    "unsafe.disableApiFiltering" to GrantPresentation(R.string.InuPluginGrantUnsafeDisableApiFiltering, R.drawable.msg_block),
)

internal val GRANT_INFO: Map<String, Int> = mapOf(
    "notifications.suppress" to R.string.InuPluginGrantNotificationsSuppressInfo,
    "takeout" to R.string.InuPluginGrantTakeoutInfo,
    "unsafe.fs" to R.string.InuPluginGrantUnsafeFsInfo,
    "unsafe.invokeRaw" to R.string.InuPluginGrantUnsafeInvokeRawInfo,
    "unsafe.jvm" to R.string.InuPluginGrantUnsafeJvmInfo,
    "unsafe.xposed" to R.string.InuPluginGrantUnsafeXposedInfo,
    "unsafe.notificationCenter" to R.string.InuPluginGrantUnsafeNotificationCenterInfo,
    "unsafe.disableApiFiltering" to R.string.InuPluginGrantUnsafeDisableApiFilteringInfo,
)
