import type { Catalog, GrantTier, ScopeKind } from '@inugram/plugin-types/grants'
import fs from 'node:fs/promises'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { rootDir } from './config.js'
import { step, success } from './lib.js'

// `sdk/types/grants.json` is the hand-written grant catalogue, published to plugin authors as part
// of the types package and read as it is by the cli. this renders it into InuCore's `GrantCatalog`,
// so the app and the cli refuse exactly the same manifest. its shape is `sdk/types/grants.d.ts`.

const catalogFile = join(rootDir, 'sdk/types/grants.json')
const outFile = join(rootDir, 'src/core/src/main/kotlin/desu/inugram/core/plugins/GrantCatalog.kt')
const sheetFile = join(rootDir, 'src/fork/ui/settings/GrantPresentations.kt')

const SCOPE_KINDS: ScopeKind[] = ['none', 'list', 'domain', 'fsSize', 'rpcMethod', 'updateType']
const TIERS: GrantTier[] = ['neutral', 'caution', 'dangerous']

export function validateCatalog(catalog: Catalog, where = catalogFile) {
  if (!Number.isInteger(catalog.pluginApi)) throw new Error(`${where}: pluginApi must be an integer`)
  if (catalog.grants.length === 0) throw new Error(`${where}: no grants`)
  const seen = new Set<string>()
  for (const grant of catalog.grants) {
    if (seen.has(grant.name)) throw new Error(`${where}: '${grant.name}' is declared twice`)
    seen.add(grant.name)
    if (!SCOPE_KINDS.includes(grant.scopes)) throw new Error(`${where}: '${grant.name}' has unknown scope kind '${grant.scopes}'`)
    if (!TIERS.includes(grant.tier)) throw new Error(`${where}: '${grant.name}' has unknown tier '${grant.tier}'`)
    if (grant.tierWhenUnscoped && !TIERS.includes(grant.tierWhenUnscoped)) {
      throw new Error(`${where}: '${grant.name}' has unknown tierWhenUnscoped '${grant.tierWhenUnscoped}'`)
    }
    if ((grant.scopes === 'list') !== (grant.values !== undefined)) {
      throw new Error(`${where}: '${grant.name}' must list its values if and only if it is a 'list' grant`)
    }
    if (grant.scopes === 'none' && (grant.tierWhenUnscoped || grant.extraValues)) {
      throw new Error(`${where}: '${grant.name}' takes no scopes, so it has no unscoped form`)
    }
    if (grant.description.trim() === '') throw new Error(`${where}: '${grant.name}' has no description`)
  }
}

/** a kotlin string literal. the catalogue holds regexes, so the escaping has to be real */
function kt(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/\n/g, '\\n')
  return `"${escaped}"`
}

function ktSet(values: string[], indent = ''): string {
  if (values.length === 0) return 'emptySet()'
  const inline = `setOf(${values.map(kt).join(', ')})`
  if (inline.length + indent.length <= 110) return inline
  return `setOf(\n${values.map(value => `${indent}    ${kt(value)},`).join('\n')}\n${indent})`
}

function ktTier(tier: GrantTier | undefined): string {
  return tier ? `GrantTier.${tier.toUpperCase()}` : 'null'
}

function renderSheet(catalog: Catalog): string {
  const rows = catalog.grants.map(grant => `    ${kt(grant.name)} to GrantPresentation(R.string.${grant.title}, R.drawable.${grant.icon}),`)
  const info = catalog.grants
    .filter(grant => grant.info)
    .map(grant => `    ${kt(grant.name)} to R.string.${grant.info},`)

  return `package desu.inugram.ui.settings

// GENERATED by \`pnpm run generate-grants\` from sdk/types/grants.json.

import org.telegram.messenger.R

internal class GrantPresentation(val titleRes: Int, val iconRes: Int)

internal val KNOWN_GRANTS: Map<String, GrantPresentation> = mapOf(
${rows.join('\n')}
)

internal val GRANT_INFO: Map<String, Int> = mapOf(
${info.join('\n')}
)
`
}

function render(catalog: Catalog): string {
  const entries = catalog.grants.map((grant) => {
    const fields = [
      `name = ${kt(grant.name)}`,
      `scopes = ScopeKind.${grant.scopes.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase()}`,
      `values = ${ktSet(grant.values ?? [], '            ')}`,
      `extraValues = ${ktSet(grant.extraValues ?? [], '            ')}`,
      `refusesTakeover = ${grant.refusesTakeover === true}`,
      `tier = ${ktTier(grant.tier)}`,
      `tierWhenUnscoped = ${ktTier(grant.tierWhenUnscoped)}`,
    ]
    return `        Entry(\n${fields.map(f => `            ${f},`).join('\n')}\n        ),`
  })

  return `package desu.inugram.core.plugins

// GENERATED by \`pnpm run generate-grants\` from sdk/types/grants.json.

enum class ScopeKind {
    NONE,
    LIST,
    DOMAIN,
    FS_SIZE,
    RPC_METHOD,
    UPDATE_TYPE,
}

enum class GrantTier {
    NEUTRAL,
    CAUTION,
    DANGEROUS,
}

object GrantCatalog {
    /** the \`@plugin-api\` level this app implements */
    const val PLUGIN_API = ${catalog.pluginApi}

    class Entry(
        val name: String,
        val scopes: ScopeKind,
        val values: Set<String>,
        val extraValues: Set<String>,
        val refusesTakeover: Boolean,
        val tier: GrantTier,
        val tierWhenUnscoped: GrantTier?,
    )

    private val ENTRIES: List<Entry> = listOf(
${entries.join('\n')}
    )

    private val BY_NAME: Map<String, Entry> = ENTRIES.associateBy { it.name }
    private val DOMAIN = Regex(${kt(catalog.patterns.domain)})
    private val FS_SIZE = Regex(${kt(catalog.patterns.fsSize)}, RegexOption.IGNORE_CASE)
    private val TAKEOVER_METHODS: Set<String> = ${ktSet(catalog.takeoverMethods.names, '    ')}
    val UNDELIVERABLE_UPDATES: Set<String> = ${ktSet(catalog.undeliverableUpdates.names, '    ')}

    val names: Set<String> get() = BY_NAME.keys
    fun findEntry(name: String): Entry? = BY_NAME[name]
    fun isDomain(scope: String): Boolean = DOMAIN.matches(scope)
    fun fsSizeMatch(scope: String): MatchResult? = FS_SIZE.matchEntire(scope.trim())
    fun isTakeoverMethod(name: String): Boolean =
        ${catalog.takeoverMethods.prefixes.map(prefix => `name.startsWith(${kt(prefix)}) || `).join('')}name in TAKEOVER_METHODS

    fun resolveTier(name: String, scopes: List<String>?): GrantTier {
        val entry = BY_NAME[name] ?: return GrantTier.NEUTRAL
        val unscoped = entry.tierWhenUnscoped
        if (scopes == null && unscoped != null && unscoped > entry.tier) return unscoped
        return entry.tier
    }
}
`
}

export async function generateGrants(): Promise<boolean> {
  const catalog = JSON.parse(await fs.readFile(catalogFile, 'utf8')) as Catalog
  validateCatalog(catalog)
  let changed = false
  for (const [file, body] of [[outFile, render(catalog)], [sheetFile, renderSheet(catalog)]] as const) {
    if (await fs.readFile(file, 'utf8').catch(() => null) === body) continue
    step(`Generating ${file}`)
    await fs.writeFile(file, body)
    changed = true
  }
  if (changed) success('grant catalogue generated')
  return changed
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await generateGrants()
}
